//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mircar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renta_Devolucion
    {
        public int id { get; set; }
        public int id_empleado { get; set; }
        public string Vehiculo { get; set; }
        public string cliente { get; set; }
        public System.DateTime Fecha_renta { get; set; }
        public System.DateTime Fecha_devolucion { get; set; }
        public decimal monto { get; set; }
        public int Cantidad_Dias { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
    }
}
