//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mircar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public int id { get; set; }
        public string Descripcion { get; set; }
        public int No_chasis { get; set; }
        public int No_motor { get; set; }
        public int No_placa { get; set; }
        public string Tipo_Vehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Tipo_Combustible { get; set; }
        public string Estado { get; set; }
    }
}
